### PR TITLE
Rebrand soft launch

### PR DESCRIPTION
**Pull request by marcusrelacion**

### CODE REVIEW

**Comment by marcusrelacion** [comment]
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Firefox 90.0 on Mac OS 10.15
Viewport:  3428 x 1266 @1x
Language:  en-US
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2F&os=OS+X&os_version=Catalina&browser=Firefox&browser_version=90.0&resolution=3428x1266&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-359--dcdesignweek.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60e4ce17770c250008906274&commentID=60e4d3ff9c7c8747073bb6d0&resolution=resolved)

**Comment by marcusrelacion** [comment]
Created a new issue [Issue Test #360](https://github.com/AIGAdc/dcdesignweek.org/issues/360) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [Headings on events page should be logically ordered #362](https://github.com/AIGAdc/dcdesignweek.org/issues/362) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [Navigation should belong within a `<header>` landmark outside the `<main>` #363](https://github.com/AIGAdc/dcdesignweek.org/issues/363) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [Offscreen menu should be labelled appropriately and not be accessible when visually hidden  #364](https://github.com/AIGAdc/dcdesignweek.org/issues/364) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [Email address ID has typo #365](https://github.com/AIGAdc/dcdesignweek.org/issues/365) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [The offscreen menu should be next in the tab order upon opening the menu #366](https://github.com/AIGAdc/dcdesignweek.org/issues/366) in GitHub

**Comment by kirstengreen** [comment]
Created a new issue [Focus state on events card #368](https://github.com/AIGAdc/dcdesignweek.org/issues/368) in GitHub

**Comment by kirstengreen** [comment]
Created a new issue [Sort accordion hover state #369](https://github.com/AIGAdc/dcdesignweek.org/issues/369) in GitHub

**Comment by kirstengreen** [comment]
Created a new issue [Only header in sponsors with strange spacing #370](https://github.com/AIGAdc/dcdesignweek.org/issues/370) in GitHub

**Comment by kirstengreen** [comment]
Created a new issue [Clear filters is resting directly on top of the first event card #371](https://github.com/AIGAdc/dcdesignweek.org/issues/371) in GitHub

**Comment by kirstengreen** [comment]
Created a new issue [No spacing between events cards #372](https://github.com/AIGAdc/dcdesignweek.org/issues/372) in GitHub

**Comment by kirstengreen** [comment]
Created a new issue [No spacing between button and image #373](https://github.com/AIGAdc/dcdesignweek.org/issues/373) in GitHub

**Comment by kirstengreen** [comment]
Created a new issue [No spacing between member cards #374](https://github.com/AIGAdc/dcdesignweek.org/issues/374) in GitHub

**Comment by kirstengreen** [comment]
Created a new issue [Event Page - Speakers margins are collapsed #375](https://github.com/AIGAdc/dcdesignweek.org/issues/375) in GitHub

**Comment by kirstengreen** [comment]
Created a new issue [Events Page - Ticket buttons have no space between #376](https://github.com/AIGAdc/dcdesignweek.org/issues/376) in GitHub

**Comment by kirstengreen** [comment]
Created a new issue [Event Page - No space above details header #377](https://github.com/AIGAdc/dcdesignweek.org/issues/377) in GitHub

**Comment by kirstengreen** [comment]
Created a new issue [FAQ contact info spacing is close to the last question #378](https://github.com/AIGAdc/dcdesignweek.org/issues/378) in GitHub

**Comment by kirstengreen** [comment]
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /faqs/
Browser:   Firefox 92.0 on Windows 10
Viewport:  1275 x 921 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2Ffaqs%2F&os=Windows&os_version=10&browser=Firefox&browser_version=92.0&resolution=1275x921&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-359--dcdesignweek.netlify.app/faqs/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6115c85f2908b200087f93af&commentID=6116ca4edebe0c00b10ee9ad&resolution=resolved)

**Comment by kirstengreen** [comment]
Created a new issue [Tablet VP - Should this be 1 column? #379](https://github.com/AIGAdc/dcdesignweek.org/issues/379) in GitHub

**Comment by marcusrelacion** [comment]
Created a new issue [Subscribe form validation border #380](https://github.com/AIGAdc/dcdesignweek.org/issues/380) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Navigation #381](https://github.com/AIGAdc/dcdesignweek.org/issues/381) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Hero Elements #382](https://github.com/AIGAdc/dcdesignweek.org/issues/382) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Content Update #383](https://github.com/AIGAdc/dcdesignweek.org/issues/383) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Section Containers #384](https://github.com/AIGAdc/dcdesignweek.org/issues/384) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Sponsors Elements #385](https://github.com/AIGAdc/dcdesignweek.org/issues/385) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Background Image #386](https://github.com/AIGAdc/dcdesignweek.org/issues/386) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Section Images #387](https://github.com/AIGAdc/dcdesignweek.org/issues/387) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Hero Elements #388](https://github.com/AIGAdc/dcdesignweek.org/issues/388) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Events Section #389](https://github.com/AIGAdc/dcdesignweek.org/issues/389) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Hero Section #390](https://github.com/AIGAdc/dcdesignweek.org/issues/390) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Partner Content #391](https://github.com/AIGAdc/dcdesignweek.org/issues/391) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Staff Section #392](https://github.com/AIGAdc/dcdesignweek.org/issues/392) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Staff Elements #393](https://github.com/AIGAdc/dcdesignweek.org/issues/393) in GitHub

**Comment by silviascript** [comment]
Created a new issue [FAQs Elements #394](https://github.com/AIGAdc/dcdesignweek.org/issues/394) in GitHub

**Comment by silviascript** [comment]
Created a new issue [FAQs Styling #395](https://github.com/AIGAdc/dcdesignweek.org/issues/395) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Makers Page #396](https://github.com/AIGAdc/dcdesignweek.org/issues/396) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Hero Styling #397](https://github.com/AIGAdc/dcdesignweek.org/issues/397) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Hero About Styling #398](https://github.com/AIGAdc/dcdesignweek.org/issues/398) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Hero Event Styling #399](https://github.com/AIGAdc/dcdesignweek.org/issues/399) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Event Description Styling #400](https://github.com/AIGAdc/dcdesignweek.org/issues/400) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Speaker Accordion #401](https://github.com/AIGAdc/dcdesignweek.org/issues/401) in GitHub

**Comment by yxxko** [comment]
Chita Rivera Header isn’t inside the shape
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Mobile Safari 14.1.1 on iOS 14.6
Viewport:  428 x 746 @3x
Language:  en-us
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-359--dcdesignweek.netlify.app%2F&os=iOS&os_version=14.6&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-359--dcdesignweek.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6117f1ac44e60800087b34c3&commentID=61191131f4ea7a7ede7c1121&resolution=resolved)

**Comment by yxxko** [comment]
Created a new issue [Chita Rivera Header #402](https://github.com/AIGAdc/dcdesignweek.org/issues/402) in GitHub

**Comment by yxxko** [comment]
Created a new issue [DCDW hero on the homepage hierarchy #403](https://github.com/AIGAdc/dcdesignweek.org/issues/403) in GitHub

**Comment by yxxko** [comment]
Created a new issue [Larger H1s on mobile #404](https://github.com/AIGAdc/dcdesignweek.org/issues/404) in GitHub

**Comment by yxxko** [comment]
Created a new issue [Date on the event cards is up against the left edge of the screen #405](https://github.com/AIGAdc/dcdesignweek.org/issues/405) in GitHub

**Comment by yxxko** [comment]
Created a new issue [Styling issue on speaker about in individual event page #406](https://github.com/AIGAdc/dcdesignweek.org/issues/406) in GitHub

**Comment by yxxko** [comment]
Created a new issue [Disco Dan sponsor header not filling into the shape #410](https://github.com/AIGAdc/dcdesignweek.org/issues/410) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Header Inconsistencies #411](https://github.com/AIGAdc/dcdesignweek.org/issues/411) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Image Spacing #412](https://github.com/AIGAdc/dcdesignweek.org/issues/412) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Photos Credit Graphic #413](https://github.com/AIGAdc/dcdesignweek.org/issues/413) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Hero Content Spacing #414](https://github.com/AIGAdc/dcdesignweek.org/issues/414) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Accessibility Hero #415](https://github.com/AIGAdc/dcdesignweek.org/issues/415) in GitHub

**Comment by yxxko** [comment]
Created a new issue [Disco Dan sponsor title not fitting the shape #416](https://github.com/AIGAdc/dcdesignweek.org/issues/416) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [Skip to main content should meet color contrast requirements  #418](https://github.com/AIGAdc/dcdesignweek.org/issues/418) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [Error messages should have a higher color contrast ratio #420](https://github.com/AIGAdc/dcdesignweek.org/issues/420) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [Skip to main should skip to the `h1` on the page #421](https://github.com/AIGAdc/dcdesignweek.org/issues/421) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [Links should be styled as links and match the accessible label #422](https://github.com/AIGAdc/dcdesignweek.org/issues/422) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [Error messages do not read out to screen readers #423](https://github.com/AIGAdc/dcdesignweek.org/issues/423) in GitHub

**Comment by joshkimux** [comment]
Created a new issue [Contact on FAQs should be a `h2` #425](https://github.com/AIGAdc/dcdesignweek.org/issues/425) in GitHub

**Pull request merged**
