### PR TITLE
2021 Prep

### PR DESCRIPTION
**Pull request by marcusrelacion**

### CODE REVIEW

**Comment by yxxko** [comment]
Created a new issue [Add Hoverstate #346](https://github.com/AIGAdc/dcdesignweek.org/issues/346) in GitHub

**Comment by yxxko** [comment]
<details><summary>Comment has been resolved by Marcus Relacion</summary>

Coming back is a lil off
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 90.0.4430.212 on Windows 10
Viewport:  2896 x 1486 @1.25x
Language:  en-US
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-345--dcdesignweek.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=90.0&resolution=2896x1486&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-345--dcdesignweek.netlify.app/) · [Mark as Unresolved](https://app.netlify.com/cdp/resolve?deployID=60b829f4f7c7750007e7ea77&commentID=60b82df30f6f4d3ebb88b31f&resolution=unresolved)

</details>

**Comment by silviascript** [comment]
Created a new issue [Navigation Alignment #347](https://github.com/AIGAdc/dcdesignweek.org/issues/347) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Font Rendering #348](https://github.com/AIGAdc/dcdesignweek.org/issues/348) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Button Hover State #349](https://github.com/AIGAdc/dcdesignweek.org/issues/349) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Label Alignment #350](https://github.com/AIGAdc/dcdesignweek.org/issues/350) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Button Padding #351](https://github.com/AIGAdc/dcdesignweek.org/issues/351) in GitHub

**Comment by silviascript** [comment]
Created a new issue [Heart Spacing #352](https://github.com/AIGAdc/dcdesignweek.org/issues/352) in GitHub

**Pull request merged**
