### PR TITLE
2016 Archive

### PR DESCRIPTION
**Pull request by marcusrelacion**
This pull request creates a working archive of the 2016 DC Design Week website as mentioned in #33. 

- A prominent bar has been placed at the top of every page within the `2016` archive to inform visitors that they are viewing an archived copy of the DC Design Week site as it would have appeared in 2016. There is also a link pointing them to the github repo where they can find more information regarding the current site.
- `2016` folder that is a duplicate of the `_site` folder and contains a compiled, working version of the 2016 site.
- All navigation and button links have been updated to allow users to fully navigate through the site as though it were still live.

Attached is the bar on the home page.

screenshot 2017-06-20 18 39 09

### CODE REVIEW

**Comment by DanRader** [comment]
When this gets pushed, where will the current Url point to?

**Comment by marcusrelacion** [comment]
@DanRader the url will still be dcdesignweek.org 

Once this is merged, you'll be able to access the 2016 folder by going to `dcdesignweek.org/2016/`

**Comment by DanRader** [comment]
But when this is merged will there be a duplicate of the site on dcdesignweek.org as well as dcdesignweek.org/2016?

Just want to make sure it's not a blank page as we build the 'coming soon' landing page

**Comment by marcusrelacion** [comment]
@DanRader it should still work as normal. The overall site should be unaffected since the only thing that is being merged is the `2016` folder that contains a copy of the compiled site.

**Comment by DanRader** [comment]
approved.💥  KABLAMO 💥

official AF 👨🏻‍⚖️

**Pull request merged**
